name: Update profile metrics

on:
  schedule:
    - cron: "0 */12 * * *"   # runs every 12 hours
  workflow_dispatch:          # lets you trigger it manually from the Actions tab
  push:
    branches:
      - main

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: akhildas675
          template: terminal
          base: header, metadata, activity, community, repositories
          plugin_languages: yes
          plugin_lines: yes
          plugin_stars: yes
          plugin_followup: yes
          config_timezone: Asia/Kolkata
